baseurl = "/"
title = "東億事件簿"

languageCode = "zh-hant"
theme = "hugo-steam-theme"
googleAnalytics = "UA-50381786-4"


paginate = 10

[params]

  title = "東億紙廠空汙事件簿"

  # subtitle = "a minimal theme for ~~Ghost~~ Hugo"
  copyright = "Released under the MIT license."

  # You can choose between green, orange, red and blue.
  themeColor = "green"
  